
import java.awt.Label;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Juan Pedro Gil
 */
public class Gauss extends javax.swing.JFrame {
    DefaultTableModel model,model2,model3;
    double[][] matrizThis,matrizO;
    /**
     * Creates new form Guass
     */
    public Gauss() {
        initComponents();
        this.setLocationRelativeTo(null);
        model=new DefaultTableModel();
        model.addColumn("x1");
        model.addColumn("x2");
        model.addColumn("x3");
        model.addColumn("VD");
        tabla1.setModel(model);
        /////////////////////
        model2=new DefaultTableModel();
        model2.addColumn("x1");
        model2.addColumn("x2");
        model2.addColumn("x3");
        model2.addColumn("VD");
        tabla2.setModel(model2);
        //////////////////////
        model3=new DefaultTableModel();
        model3.addColumn("x1");
        model3.addColumn("x2");
        model3.addColumn("x3");
        model3.addColumn("VD");
        tabla3.setModel(model3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla3 = new javax.swing.JTable();
        x1 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        x3 = new javax.swing.JLabel();
        btnMP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gauss Normal");
        setResizable(false);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla1.setEnabled(false);
        jScrollPane1.setViewportView(tabla1);

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla2.setEnabled(false);
        jScrollPane2.setViewportView(tabla2);

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla3.setEnabled(false);
        jScrollPane3.setViewportView(tabla3);

        x1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        x2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        x3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnMP.setText("Menu Principal");
        btnMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(x2)
                            .addComponent(x1)
                            .addComponent(x3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMP, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(x1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x3)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMPActionPerformed
        // TODO add your handling code here:
        matrizO=new double[3][4];
        for(int i=0;i<3;i++){
            for(int j=0;j<4;j++){
                matrizO[i][j]=Double.parseDouble(model.getValueAt(i, j).toString());
            }
        }
        VentanaGauss menu=new VentanaGauss();
        menu.start(matrizO);
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMPActionPerformed

    /**
     * @param args the command line arguments
     */
    private void asignar(double[][] mat,DefaultTableModel m){
        while(m.getRowCount()!=0){
            m.removeRow(0);
        }
        for(int i=0;i<3;i++){
            Object[] object=new Object[4];
            object[0]=mat[i][0];
            object[1]=mat[i][1];
            object[2]=mat[i][2];
            object[3]=mat[i][3];
            m.addRow(object);
        }
    }
    public void start(double[][] matriz){
        matrizThis=matriz;
        asignar(matrizThis,model);
        matrizThis=gauss(0,0,matrizThis);
        asignar(matrizThis,model2);
        matrizThis=gauss(1,1,matrizThis);
        asignar(matrizThis,model3);
        calcXs(model3,x1,x2,x3);
    }
    private double[][] gauss(int fila,int col,double[][] matriz){
        double dato=matriz[fila][col];
        if(fila==0){
            double dp=matriz[1][0]/dato;
            for(int i=1;i<3;i++){
                for(int j=0;j<4;j++){
                    matriz[i][j]=matriz[i][j]-dp*matriz[0][j];
                }
                dp=matriz[2][0]/dato;
            }
        }
        if(fila==1){
            double dp=matriz[2][1]/dato;
            for(int i=0;i<4;i++){
                matriz[2][i]=matriz[2][i]-dp*matriz[1][i];
            }
        }
        return matriz;
    }
    private void calcXs(DefaultTableModel m,JLabel lx,JLabel lx2,JLabel lx3){
        double x3=Double.parseDouble(m.getValueAt(2,3).toString())/Double.parseDouble(m.getValueAt(2,2).toString());
        double x2=(Double.parseDouble(m.getValueAt(1,3).toString())-Double.parseDouble(m.getValueAt(1,2).toString())*x3)/Double.parseDouble(m.getValueAt(1,1).toString());
        double x1=(
                Double.parseDouble(m.getValueAt(0,3).toString())-Double.parseDouble(m.getValueAt(0,1).toString())*x2-Double.parseDouble(m.getValueAt(0,2).toString())*x3
                )/Double.parseDouble(m.getValueAt(0,0).toString());
        lx.setText("X1= "+x1);
        lx2.setText("X2= "+x2);
        lx3.setText("X3= "+x3);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gauss.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gauss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    private javax.swing.JTable tabla3;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel x3;
    // End of variables declaration//GEN-END:variables
}
